#!/usr/bin/env bash
# Builds the server binary and installs the global `r2` command into your PATH.
# Re-run this any time to rebuild and reinstall.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BINDIR="${BINDIR:-$HOME/.local/bin}"
WRAPPER="$BINDIR/r2"

echo "→ building server binary…"
( cd "$REPO" && go build -o "$REPO/bin/r2-server" . )

mkdir -p "$BINDIR" "$REPO/.run"

echo "→ installing wrapper → $WRAPPER"
cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# Auto-generated by $REPO/install.sh — controls the R2 file manager server.
set -euo pipefail
REPO="$REPO"
PIDFILE="\$REPO/.run/r2.pid"
LOGFILE="\$REPO/.run/r2.log"

running() { [ -f "\$PIDFILE" ] && kill -0 "\$(cat "\$PIDFILE")" 2>/dev/null; }

start() {
  if running; then
    echo "r2 already running (pid \$(cat "\$PIDFILE"))"
    grep -m1 'running at' "\$LOGFILE" 2>/dev/null || true
    exit 0
  fi
  cd "\$REPO"
  nohup "\$REPO/bin/r2-server" >"\$LOGFILE" 2>&1 &
  echo \$! > "\$PIDFILE"
  sleep 0.4
  if ! running; then
    echo "r2 failed to start:"; cat "\$LOGFILE"; rm -f "\$PIDFILE"; exit 1
  fi
  grep -m1 'running at' "\$LOGFILE" 2>/dev/null || echo "r2 started (pid \$(cat "\$PIDFILE"))"
}

die() {
  if running; then
    kill "\$(cat "\$PIDFILE")" && rm -f "\$PIDFILE"
    echo "r2 stopped"
  else
    echo "r2 not running"; rm -f "\$PIDFILE" 2>/dev/null || true
  fi
}

case "\${1:-start}" in
  ""|start)   start ;;
  die|stop)   die ;;
  restart)    die || true; start ;;
  status)     running && echo "r2 running (pid \$(cat "\$PIDFILE"))" || echo "r2 not running" ;;
  logs)       tail -f "\$LOGFILE" ;;
  *) echo "usage: r2 [start|die|restart|status|logs]"; exit 1 ;;
esac
EOF
chmod +x "$WRAPPER"

echo
echo "✓ installed."
[ -f "$REPO/.env" ] || echo "⚠ no .env found — copy .env.example to .env and fill it in before running 'r2'."
case ":$PATH:" in
  *":$BINDIR:"*) : ;;
  *) echo "⚠ $BINDIR is not on your PATH. Add this to your shell rc:"
     echo "    export PATH=\"$BINDIR:\$PATH\"" ;;
esac
echo
echo "Usage: r2 [start|die|restart|status|logs]"
